exec wmname LG3D &
exec wmname &

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh &

eval $(/usr/bin/gnome-keyring-daemon --start) &
export SSH_AUTH_SOCK &

mkdir -p "$HOME"/.local/share/keyrings &

xrdb ~/.Xresources &

exec dbus-launch bspwm
